### ISSUE TITLE
In file not-really-a-framework/nraf/app.js. 

### ISSUE THREAD

**Issue by fxnoob** [vipulbhj/nraf#4]
https://github.com/vipulbhj/not-really-a-framework/blob/76c91fa54a165d53f9f09148b6ed588a218281b1/nraf/app.js#L74

**Comment by fxnoob** [comment]
that will run only one time, after that response will be static

**Comment by fxnoob** [comment]
see
https://github.com/fxnoob/DExpress/blob/1ed9dc97b5866e9968979df9bba56a53ce0c6fac/lib/index.ts#L21

**Comment by fxnoob** [comment]
my bad. got the point.

**Comment by vipulbhj** [comment]
This is not really a bug as the use case is different. If you go back to express and look at the typical usage, the usage of get and post is something like `get(endpoint, function)`.

This second parameter function is the space where user writes a function(expected) which will handle all the requests to that url after middlewares apllied before. And as the function createServer is called on reach request recieved by the server, there are no static responses and they depand on every single request. Tho, it is true that they are not sockets and data transfer is req->res and end. Over to next request
