### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by vipulbhj** [vipulbhj/nraf#9]
I am offering rupees 5K as compensation, to help with documentation a basic version of NRAF.

# Requirements:

- [x] Basic documentation for core API docs.
- [x] Basic documentation for the core templating engine.
- [x] Quick start tutorial.

200 - 500 words per section, I can assist with basic knowledge transfer.

**Comment by heyanurag** [comment]
Would love to help!
Although I don't have a lot of experience in documentation but I am confident in finding my way through!😅

**Comment by vipulbhj** [comment]
Sure @heyanurag go ahead. I would recommend start by looking at the `examples/Todo`. I can answer questions you have ?

**Comment by heyanurag** [comment]
On it! Shall I create a new branch locally with markdown files or prepare a draft on Notion?

**Comment by vipulbhj** [comment]
Whatever feels more comfortable, just keep me in the loop 😛

**Comment by heyanurag** [comment]
Hey @vipulbhj, below is the draft of the core API.

[https://iodized-coast-533.notion.site/Core-API-c1efb2fa698d4506b96f85379e2c90f8](url)

Also,
I did not understand the goal and implementation of the `serverPublicAssets()` and `match()` functions in the NRAF app!
Could you please explain those to me?

**Comment by vipulbhj** [comment]
Could you drop me a message on Twitter DMs.

I will send you a google meet link, and we can discuss things :)

**Comment by vipulbhj** [comment]
Assigned to @heyanurag. Not open anymore :)

**Comment by heyanurag** [comment]
![terminal](https://user-images.githubusercontent.com/63957920/149618238-a2244e9c-d750-47e1-aa86-0f1415768643.png)
![webpage](https://user-images.githubusercontent.com/63957920/149618243-4b795edf-71a7-42da-9520-d20bf5e8001a.png)
![Logo](https://user-images.githubusercontent.com/63957920/149619576-3df47314-2d3e-4d50-8e12-da5bb4ab9b77.png)

Using these image links in the docs to maintain small repository size.
